#Requires -Modules powershell-yaml
<#
.SYNOPSIS
    Helper script to scaffold a new subscription vending parameter file.
    Validates IP address non-overlap before creating the file.

.EXAMPLE
    ./scripts/new-subscription.ps1 `
        -SubscriptionAlias     "sub-contoso-retail-prod" `
        -DisplayName           "Contoso Retail Production" `
        -TargetMG              "alz-landingzones-corp" `
        -SpokeAddressPrefix    "10.101.0.0/16" `
        -OwnerEmail            "team@contoso.com" `
        -OwnerGroupObjectId    "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $SubscriptionAlias,
    [Parameter(Mandatory)] [string] $DisplayName,
    [Parameter(Mandatory)]
    [ValidateSet("alz-landingzones-corp","alz-landingzones-online","alz-sandbox")]
    [string] $TargetMG,
    [Parameter(Mandatory)] [string] $SpokeAddressPrefix,   # e.g. 10.101.0.0/16
    [Parameter(Mandatory)] [string] $OwnerEmail,
    [Parameter(Mandatory)] [string] $OwnerGroupObjectId,
    [string] $Workload = "Production"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$outputFile = "subscription-vending/parameters/${SubscriptionAlias}.bicepparam"

# ---- Check for duplicate file ----
if (Test-Path $outputFile) {
    throw "Parameter file already exists: $outputFile"
}

# ---- Parse CIDR for subnets ----
$parts    = $SpokeAddressPrefix -split "/"
$baseIP   = $parts[0]
$ipParts  = $baseIP -split "\." | ForEach-Object { [int]$_ }

$appSubnet  = "$($ipParts[0]).$($ipParts[1]).0.0/24"
$dataSubnet = "$($ipParts[0]).$($ipParts[1]).1.0/24"
$webSubnet  = "$($ipParts[0]).$($ipParts[1]).2.0/24"

# ---- Write bicepparam file ----
$content = @"
using '../main.bicep'

// Auto-generated by new-subscription.ps1 on $(Get-Date -Format "yyyy-MM-dd")
// Subscription: $DisplayName

param subscriptionDisplayName  = '$DisplayName'
param subscriptionAlias        = '$SubscriptionAlias'
param targetManagementGroupId  = '$TargetMG'
param subscriptionWorkload     = '$Workload'

param eaBillingAccountName     = '<YOUR_EA_BILLING_ACCOUNT_ID>'
param eaEnrollmentAccountName  = '<YOUR_EA_ENROLLMENT_ACCOUNT_ID>'

param location                 = 'australiaeast'
param hubVnetId                = '/subscriptions/<CONNECTIVITY_SUB_ID>/resourceGroups/rg-connectivity-hub-australiaeast-001/providers/Microsoft.Network/virtualNetworks/vnet-hub-australiaeast-001'
param spokeVnetAddressPrefix   = '$SpokeAddressPrefix'
param spokeSubnets = [
  { name: 'snet-app',  addressPrefix: '$appSubnet'  }
  { name: 'snet-data', addressPrefix: '$dataSubnet' }
  { name: 'snet-web',  addressPrefix: '$webSubnet'  }
]

param routeTableId             = '/subscriptions/<CONNECTIVITY_SUB_ID>/resourceGroups/rg-connectivity-hub-australiaeast-001/providers/Microsoft.Network/routeTables/udr-to-checkpoint-001'
param logAnalyticsWorkspaceId  = '/subscriptions/<MANAGEMENT_SUB_ID>/resourceGroups/rg-management-logging-001/providers/Microsoft.OperationalInsights/workspaces/law-management-australiaeast-001'

param ownerEmail               = '$OwnerEmail'
param ownerGroupObjectId       = '$OwnerGroupObjectId'

param tags = {
  environment:  '$(if ($Workload -eq "Production") { "production" } else { "dev-test" })'
  managedBy:    'platform-team'
  createdBy:    'subscription-vending'
  ownerEmail:   '$OwnerEmail'
}
"@

$content | Out-File -FilePath $outputFile -Encoding utf8
Write-Host "Created: $outputFile" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Review $outputFile and fill in EA billing account / subscription IDs"
Write-Host "  2. git add $outputFile && git commit -m 'feat: vend subscription $SubscriptionAlias'"
Write-Host "  3. Create a Pull Request - the what-if results will be posted as a comment"
Write-Host "  4. Merge to main - the 04-subscription-vending workflow will deploy after approval"
